export interface CrosswordEntry { answer: string; clue: string; }

export const CROSSWORD_BANK: CrosswordEntry[] = [
  {answer:"amber",clue:"Golden fossil resin"},{answer:"apple",clue:"Fruit that may be baked into a pie"},
  {answer:"arise",clue:"Get up"},{answer:"atlas",clue:"Book of maps"},{answer:"beach",clue:"Sandy shoreline"},
  {answer:"beard",clue:"Chin growth"},{answer:"bench",clue:"Park seat"},{answer:"berry",clue:"Small juicy fruit"},
  {answer:"birch",clue:"Tree with papery bark"},{answer:"blade",clue:"Cutting edge"},{answer:"brain",clue:"Thinking organ"},
  {answer:"bread",clue:"Bakery staple"},{answer:"brick",clue:"Wall unit"},{answer:"cabin",clue:"Rustic little house"},
  {answer:"candy",clue:"Sweet treat"},{answer:"chair",clue:"One-person seat"},{answer:"charm",clue:"Winning quality"},
  {answer:"chime",clue:"Bell-like sound"},{answer:"clean",clue:"Free of dirt"},{answer:"clear",clue:"Easy to understand"},
  {answer:"clock",clue:"Wall-mounted timekeeper"},{answer:"cloud",clue:"White shape in the sky"},{answer:"coast",clue:"Land beside the sea"},
  {answer:"coral",clue:"Reef builder"},{answer:"craft",clue:"Make with skill"},{answer:"crane",clue:"Tall lifting machine"},
  {answer:"cream",clue:"Rich part of milk"},{answer:"dance",clue:"Move to music"},{answer:"dream",clue:"A sleeper's story"},
  {answer:"earth",clue:"Our planet"},{answer:"elbow",clue:"Arm joint"},{answer:"ember",clue:"Glowing piece of coal"},
  {answer:"field",clue:"Open stretch of land"},{answer:"flame",clue:"Visible part of a fire"},{answer:"floor",clue:"Room surface underfoot"},
  {answer:"frame",clue:"Border around a picture"},{answer:"fresh",clue:"Newly made"},{answer:"fruit",clue:"Apple or peach"},
  {answer:"glass",clue:"Window material"},{answer:"globe",clue:"Spherical world model"},{answer:"grace",clue:"Poise and elegance"},
  {answer:"grain",clue:"Wheat or rice"},{answer:"grape",clue:"Vineyard fruit"},{answer:"graph",clue:"Data shown with lines or bars"},
  {answer:"grass",clue:"Common lawn covering"},{answer:"heart",clue:"Organ that pumps blood"},{answer:"honey",clue:"Sweet product of bees"},
  {answer:"horse",clue:"Stable resident"},{answer:"house",clue:"Place to live"},{answer:"image",clue:"Picture or likeness"},
  {answer:"lemon",clue:"Tart yellow fruit"},{answer:"light",clue:"Opposite of darkness"},{answer:"maple",clue:"Tree known for syrup"},
  {answer:"metal",clue:"Iron or copper"},{answer:"mouse",clue:"Small rodent or computer device"},{answer:"music",clue:"Organized sound"},
  {answer:"ocean",clue:"Vast body of salt water"},{answer:"olive",clue:"Small fruit used for oil"},{answer:"opera",clue:"Drama that is sung"},
  {answer:"paint",clue:"Color applied with a brush"},{answer:"paper",clue:"Notebook material"},{answer:"peach",clue:"Fuzzy stone fruit"},
  {answer:"pearl",clue:"Gem formed in an oyster"},{answer:"piano",clue:"Keyboard instrument"},{answer:"pilot",clue:"One flying a plane"},
  {answer:"plant",clue:"Green growing thing"},{answer:"plate",clue:"Dinner-table dish"},{answer:"queen",clue:"Female monarch"},
  {answer:"river",clue:"Water flowing toward a sea"},{answer:"robot",clue:"Programmable machine"},{answer:"scale",clue:"Device used to weigh"},
  {answer:"sheep",clue:"Woolly farm animal"},{answer:"shelf",clue:"Horizontal storage ledge"},{answer:"shell",clue:"Hard outer covering"},
  {answer:"shirt",clue:"Garment with sleeves"},{answer:"shore",clue:"Water's edge"},{answer:"slate",clue:"Fine-grained gray rock"},
  {answer:"smile",clue:"Happy facial expression"},{answer:"solar",clue:"Related to the sun"},{answer:"space",clue:"Room or the cosmos"},
  {answer:"spark",clue:"Tiny fiery particle"},{answer:"spice",clue:"Flavoring such as cumin"},{answer:"stage",clue:"Platform for performers"},
  {answer:"stair",clue:"One step in a staircase"},{answer:"steam",clue:"Water in vapor form"},{answer:"stone",clue:"Small piece of rock"},
  {answer:"storm",clue:"Severe weather event"},{answer:"table",clue:"Furniture with a flat top"},{answer:"tiger",clue:"Striped big cat"},
  {answer:"toast",clue:"Browned bread"},{answer:"tower",clue:"Tall narrow structure"},{answer:"trace",clue:"A very small amount"},
  {answer:"track",clue:"Path followed by a train"},{answer:"train",clue:"Railway transport"},{answer:"trend",clue:"General direction of change"},
  {answer:"water",clue:"H-two-O"},{answer:"wheel",clue:"Circular part that turns"},{answer:"world",clue:"Earth and its people"}
];
